<?
$PERM["udalennyeotrudniki"]["*"]="D";
$PERM["udalennyeotrudniki"]["3"]="X";
$PERM["sale"]["11"]="T_8";
$PERM["sale"]["10"]="T_8";
$PERM["sale"]["*"]="D";
$PERM["manage"]["10"]="T_8";
$PERM["manage"]["*"]="D";
?>